/* Form A4 as an Excel file, laid out like the printed form: countries of
 * residence down the side in the form's order, the months across, subtotals by
 * region, the grand total, then Part II (DAE-2 as counts, and volume per sex).
 *
 * Counts and totals only. The numbers are written as values, added up by
 * statistics.js from the reports on record, so the file matches what ZTIMS
 * showed on screen when it was downloaded.
 */
const ExcelJS = require('exceljs');

const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const NAVY = 'FF003D5B', BLUE = 'FF30638E', REGION = 'FFE3ECF3', SUB = 'FFDCE6EE', TOTAL = 'FFC9D9E6', GRAND = 'FFFBE6BD';
const FONT = 'Arial';
const NUM = '#,##0;-#,##0;"–"';
const thin = { style: 'thin', color: { argb: 'FFC8CED6' } };
const BOX = { top: thin, left: thin, bottom: thin, right: thin };

const sum = list => list.reduce((a, b) => a + (b || 0), 0);
const addArrays = (a, b) => a.map((v, i) => v + b[i]);

async function formA4Workbook(data) {
    const wb = new ExcelJS.Workbook();
    wb.creator = 'ZTIMS';
    const ws = wb.addWorksheet('Form A4', {
        pageSetup: { orientation: 'landscape', fitToPage: true, fitToWidth: 1, fitToHeight: 0, paperSize: 9 },
        views: [{ state: 'frozen', xSplit: 1, ySplit: 7 }]
    });
    ws.columns = [{ width: 42 }, ...MONTHS.map(() => ({ width: 9 })), { width: 11 }];
    const inRange = i => i + 1 >= data.fromMonth && i + 1 <= data.toMonth;
    const monthValues = arr => arr.map((v, i) => (inRange(i) ? v : null));

    const put = (row, values, { fill, bold, color, size, indent } = {}) => {
        const r = ws.getRow(row);
        values.forEach((v, i) => {
            const c = r.getCell(i + 1);
            c.value = v;
            c.font = { name: FONT, size: size || 10, bold: !!bold, color: { argb: color || 'FF0B0B0C' } };
            c.border = BOX;
            if (fill) c.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: fill } };
            if (i > 0) { c.numFmt = NUM; c.alignment = { horizontal: 'right' }; }
            else if (indent) c.alignment = { indent };
        });
        return r;
    };
    const rowOf = (label, arr, style) => put(r++, [label, ...monthValues(arr), sum(monthValues(arr))], style);

    // ---- title block, as on the printed form
    ws.getCell('A1').value = 'FORM A4';
    ws.getCell('A1').font = { name: FONT, size: 10, bold: true };
    ws.getCell('A2').value = 'Region VII';
    ws.getCell('A3').value = 'REPORT ON THE REGIONAL DISTRIBUTION OF TRAVELERS';
    ws.getCell('A3').font = { name: FONT, size: 14, bold: true, color: { argb: NAVY } };
    const period = data.fromMonth === 1 && data.toMonth === 12
        ? `JANUARY–DECEMBER ${data.year}`
        : `${MONTHS[data.fromMonth - 1].toUpperCase()}–${MONTHS[data.toMonth - 1].toUpperCase()} ${data.year}`;
    ws.getCell('A4').value = `${period}   ·   City/Municipality: ZAMBOANGUITA   ·   Province: NEGROS ORIENTAL`;
    ws.getCell('A5').value = `Generated by ZTIMS on ${new Date().toISOString().slice(0, 10)}. Counts only.`;
    for (const a of ['A2', 'A4', 'A5']) ws.getCell(a).font = { name: FONT, size: 10, color: { argb: 'FF52525B' } };

    let r = 7;
    put(r++, ['COUNTRY OF RESIDENCE', ...MONTHS, 'TOTAL'], { fill: NAVY, bold: true, color: 'FFFFFFFF' });

    const totalOf = code => data.counts[code].total;
    const bySection = section => data.residences.filter(x => x.section === section);

    // ---- Philippine residents
    put(r++, ['PHILIPPINE RESIDENTS', ...Array(13).fill(null)], { fill: BLUE, bold: true, color: 'FFFFFFFF' });
    let phTotal = Array(12).fill(0);
    for (const res of bySection('philippine')) {
        rowOf(res.name, totalOf(res.code), { indent: 1 });
        phTotal = addArrays(phTotal, totalOf(res.code));
    }
    rowOf('TOTAL PHILIPPINE RESIDENTS', phTotal, { fill: TOTAL, bold: true, color: NAVY });

    // ---- Non-Philippine residents, by region
    put(r++, ['NON-PHILIPPINE RESIDENTS', ...Array(13).fill(null)], { fill: BLUE, bold: true, color: 'FFFFFFFF' });
    let foreignTotal = Array(12).fill(0);
    const regions = [];
    for (const res of bySection('foreign')) {
        let g = regions.find(x => x.region === res.region);
        if (!g) regions.push(g = { region: res.region, rows: [] });
        g.rows.push(res);
    }
    for (const g of regions) {
        put(r++, [g.region.toUpperCase(), ...Array(13).fill(null)], { fill: REGION, bold: true, color: NAVY, size: 9 });
        let sub = Array(12).fill(0);
        for (const res of g.rows) {
            rowOf(res.name, totalOf(res.code), { indent: 1 });
            sub = addArrays(sub, totalOf(res.code));
        }
        rowOf(`Sub-total, ${g.region}`, sub, { fill: SUB, bold: true, indent: 1 });
        foreignTotal = addArrays(foreignTotal, sub);
    }
    rowOf('TOTAL NON-PHILIPPINE RESIDENTS', foreignTotal, { fill: TOTAL, bold: true, color: NAVY });

    const of = totalOf('overseas-filipino'), un = totalOf('unspecified');
    rowOf('Overseas Filipinos', of);
    rowOf('Guests with unspecified residence', un);
    const grand = phTotal.map((v, i) => v + foreignTotal[i] + of[i] + un[i]);
    rowOf('GRAND TOTAL GUEST ARRIVALS', grand, { fill: GRAND, bold: true, color: NAVY, size: 11 });

    // ---- Part II. A. DAE-2, as counts
    r++;
    put(r++, ['PART II. OTHER INDICATORS — A. DAE-2', ...Array(13).fill(null)], { fill: NAVY, bold: true, color: 'FFFFFFFF' });
    const d = data.dae;
    const daeRow = (label, arr, style) => put(r++, [label, ...arr, sum(arr)], { indent: 1, ...style });
    daeRow('Number of rooms', d.rooms);
    daeRow('Room-nights available (rooms × days)', d.roomNightsAvailable);
    daeRow('Room-nights occupied', d.roomNightsOccupied);
    daeRow('Room-nights not occupied', d.roomNightsNotOccupied);
    daeRow('Total guest nights', d.guestNights, { bold: true });
    ws.getCell(`A${r}`).value = 'The "Number of rooms" total adds each month\'s rooms together; the room-night rows are the counts to use.';
    ws.getCell(`A${r}`).font = { name: FONT, size: 8, italic: true, color: { argb: 'FF52525B' } };
    r++;

    // ---- Part II. B. Volume per sex
    r++;
    put(r++, ['B. VOLUME PER SEX', ...Array(13).fill(null)], { fill: NAVY, bold: true, color: 'FFFFFFFF' });
    const groups = [
        ['a. Philippine residents', bySection('philippine')],
        ['b. Non-Philippine / foreign residents', bySection('foreign')],
        ['c. Overseas Filipinos', bySection('overseas_filipino')],
        ['d. Unspecified residence', bySection('unspecified')]
    ];
    const known = data.sexKnown;
    for (const [n, sex] of [['1', 'male'], ['2', 'female']]) {
        put(r++, [`${n}. ${sex === 'male' ? 'Male' : 'Female'}`, ...Array(13).fill(null)], { fill: REGION, bold: true, color: NAVY });
        let tot = Array(12).fill(0);
        for (const [label, list] of groups) {
            const arr = Array(12).fill(0);
            for (const res of list) data.counts[res.code][sex].forEach((v, i) => { arr[i] += v; });
            tot = addArrays(tot, arr);
            // A month whose reports did not split by sex (the 2025 sheet) is left blank.
            put(r++, [label, ...arr.map((v, i) => (known[i] ? v : null)), sum(arr.map((v, i) => (known[i] ? v : 0)))], { indent: 1 });
        }
        put(r++, [`x. Total ${sex}`, ...tot.map((v, i) => (known[i] ? v : null)), sum(tot.map((v, i) => (known[i] ? v : 0)))], { fill: SUB, bold: true, indent: 1 });
    }

    // ---- sign-off
    r++;
    for (const label of ['Prepared by:', 'Signature over printed name / Date:', 'Tourism Information Officer / Statistics In-charge']) {
        ws.getCell(`A${r}`).value = label; ws.getCell(`A${r}`).font = { name: FONT, size: 10 }; r++;
    }
    r++;
    const notes = [
        '* This should be submitted to the province, then to the region.',
        '** Data per accommodation establishment is kept in ZTIMS, one report per establishment per month.'
    ];
    if (data.municipalTotalMonths.length) {
        notes.push(`Months ${data.municipalTotalMonths.map(m => MONTHS[m - 1]).join(', ')} come from the municipal totals on the printed sheet, which were not split by sex.`);
    }
    for (const note of notes) { ws.getCell(`A${r}`).value = note; ws.getCell(`A${r}`).font = { name: FONT, size: 9, italic: true, color: { argb: 'FF52525B' } }; r++; }
    ws.pageSetup.printTitlesRow = '7:7';

    return wb.xlsx.writeBuffer();
}

module.exports = { formA4Workbook };
